"""comment

Revision ID: 1603e4a2d5dc
Revises: 6df8f12acc5a
Create Date: 2025-06-23 17:22:56.732222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1603e4a2d5dc'
down_revision: Union[str, None] = '6df8f12acc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialplan', sa.Column('result', sa.String(length=20), nullable=True, comment='空号识别结果'))
    op.alter_column('dialplan', 'status',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_comment='状态',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialplan', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_comment='状态',
               existing_nullable=False)
    op.drop_column('dialplan', 'result')
    # ### end Alembic commands ###
