"""comment

Revision ID: 1e67f19ddde3
Revises: 7abc6da14c3d
Create Date: 2025-06-25 18:37:20.999894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e67f19ddde3'
down_revision: Union[str, None] = '7abc6da14c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dialplan', sa.Column('expired_at', sa.DateTime(), nullable=False, comment='过期时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dialplan', 'expired_at')
    # ### end Alembic commands ###
