"""comment

Revision ID: 311a065da014
Revises: 
Create Date: 2025-06-23 13:47:42.849657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311a065da014'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='账户 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('pwd', sa.String(length=50), nullable=False, comment='密码'),
    sa.Column('host', sa.String(length=50), nullable=False, comment='主机地址'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='客户端 ID'),
    sa.Column('uuid', sa.String(length=64), nullable=False, comment='客户端 UUID'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('dialplan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False, comment='手机号码'),
    sa.Column('client_id', sa.String(length=64), nullable=True, comment='客户端 ID'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='任务 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='任务状态'),
    sa.Column('create_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('dialplan')
    op.drop_table('client')
    op.drop_table('account')
    # ### end Alembic commands ###
