"""comment

Revision ID: 36cfcf5ef88f
Revises: 311a065da014
Create Date: 2025-06-23 14:36:53.263551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36cfcf5ef88f'
down_revision: Union[str, None] = '311a065da014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('status', sa.String(length=10), nullable=False, comment='状态'))
    op.add_column('client', sa.Column('threads_num', sa.Integer(), nullable=False, comment='线程数'))
    op.add_column('dialplan', sa.Column('task_id', sa.Integer(), nullable=False))
    op.alter_column('dialplan', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment='拨号 ID',
               existing_nullable=False,
               autoincrement=True)
    op.create_foreign_key(None, 'dialplan', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dialplan', type_='foreignkey')
    op.alter_column('dialplan', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='拨号 ID',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('dialplan', 'task_id')
    op.drop_column('client', 'threads_num')
    op.drop_column('account', 'status')
    # ### end Alembic commands ###
