"""comment

Revision ID: 6df8f12acc5a
Revises: 36cfcf5ef88f
Create Date: 2025-06-23 15:29:55.275402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6df8f12acc5a'
down_revision: Union[str, None] = '36cfcf5ef88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('client_id', sa.Integer(), nullable=True, comment='所属客户端 ID'))
    op.create_foreign_key(None, 'account', 'client', ['client_id'], ['id'])
    op.add_column('task', sa.Column('return_url', sa.String(length=255), nullable=False, comment='回调地址'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'return_url')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'client_id')
    # ### end Alembic commands ###
