"""comment

Revision ID: 7abc6da14c3d
Revises: 1603e4a2d5dc
Create Date: 2025-06-24 16:41:01.308455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7abc6da14c3d'
down_revision: Union[str, None] = '1603e4a2d5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('expired_at', sa.DateTime(), nullable=True, comment='到期时间'))
    op.drop_constraint(op.f('account_ibfk_1'), 'account', type_='foreignkey')
    op.drop_column('account', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='所属客户端 ID'))
    op.create_foreign_key(op.f('account_ibfk_1'), 'account', 'client', ['client_id'], ['id'])
    op.drop_column('account', 'expired_at')
    # ### end Alembic commands ###
